### ISSUE TITLE
Deleting accounts

### ISSUE THREAD

**Issue by kennedybaird** [nano-wallet-company/nano-wallet-desktop#24] opened 2018-06-22 06:29 UTC
Why isn't this a feature?

**Comment by devinus** [comment] 2018-06-23 00:10
The code for this actually already exists, the problem is going to be handling it gracefully. Since you cannot *actually* delete an account but merely hide it, how do we want to handle it?

See: https://github.com/nano-wallet-company/nano-wallet-desktop/blob/a76a18bdce06303f4c56913138a8e941437c832f/app/components/account-settings/component.js#L26

**Comment by kennedybaird** [comment] 2018-06-23 02:34
Thanks

I think archive is going to be the only realistic solution there.

**Comment by kennedybaird** [comment] 2018-07-02 06:49
I've been reflecting more, and something that seems to be common with banking apps is having hidden accounts.

I personally, with my banking app, have only my spending account easily visible, then have to go deeper to find my other accounts.

So I'm suggesting:

3 states for accounts

1. Normal
2. Hidden
3. Archived

The current "overview" / home page would show all the normal accounts in the carousel, then have a new page, Accounts, which will show the accounts listed by state Normal, Hidden, Archived, then name.

Also, maybe accounts can only be archived IF they have a zero balance? That would make sense.

It would also mean potentially modifying the individual account overview page + other implications.

**Comment by zhyatt** [comment] 2020-10-12 15:40
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.

**Closed by zhyatt** 2020-10-12 15:40 UTC
Labels: enhancement
