### ISSUE TITLE
Failure to launch - MacOS

### ISSUE THREAD

**Issue by GeniusUnleashed** [nano-wallet-company/nano-wallet-desktop#46] opened 2018-06-26 05:27 UTC
Last beta and current release won't open for me. I've deleted the app and redownloaded with the beta and current release and still won't open. Keeps hanging on the very last part of the process. I left it open for an entire night (overnight) and it never left this state. 
![screen shot 2018-06-25 at 10 26 22 pm](https://user-images.githubusercontent.com/17531745/41890933-dbaceac2-78c6-11e8-899a-fa00bdc7a614.png)

**Comment by kennedybaird** [comment] 2018-06-26 05:59
How are you loading the app? yarn start?

What is your system language?

**Comment by GeniusUnleashed** [comment] 2018-06-26 06:01
No clue what yarn start means. I just downloaded off the site (.dmg file)
and opened it.

**Comment by kennedybaird** [comment] 2018-06-26 06:03
If you could provide some more details someone might be able to help.

What is your system language?
What version of macOS are you running?

**Comment by GeniusUnleashed** [comment] 2018-06-26 06:05
Cool.

Latest version of MacOS 10.13.5

Not sure what you mean by language. Literally just a guy who loves Nano and
wants to help but don’t know anything about coding. I was send to Github
from Reddit.

**Comment by kennedybaird** [comment] 2018-06-26 06:06
Yeah, check the system language

 Apple menu > System Preferences, then click Language & Region

Not familiar with mac, but looking for a string somewhere like en_US or en_UK etc

Can you find that? There was an issue before about that that seems to have been resolved but maybe isn't fully.

**Comment by GeniusUnleashed** [comment] 2018-06-26 06:09
Gotcha, thanks for the walk through.

English
English (U.S.) — Primary

Region: United States

**Comment by kennedybaird** [comment] 2018-06-26 06:13
Ok, can you try something else (this might not work as not familiar with mac, google says it might)

- Open Terminal (an application on your computer - CMD+SPACE, type Terminal), it will give you a window with a black screen.
- Drag the .dmg file into the black screen
- It should open and try to start.
- Switch back to Terminal and see if there are messages there you can share with us

**Comment by GeniusUnleashed** [comment] 2018-06-26 06:18
Permission denied when I drop it in and hit enter.

**Comment by kennedybaird** [comment] 2018-06-26 06:42
I'm not sure how to debug. @devinus will be able to tell you where the log file is stored on mac, so maybe check back in 12 hours for instructions :)

**Comment by GeniusUnleashed** [comment] 2018-06-26 06:43
Will, do. Thanks!

**Comment by stefonarch** [comment] 2018-07-01 16:21
duplicate of https://github.com/nano-wallet-company/nano-wallet-desktop/issues/36 ?

**Comment by canted** [comment] 2018-07-06 23:01
I'm having the same problem, downloaded Nano.Wallet.Desktop-1.0.0-rc.3.dmg.  This is what shows up in the Console app

```
error	15:54:39.165369 -0700	nano-wallet-desktop	        AEGetDescData of non-desc type 'reco' not a good idea
default	15:54:39.257524 -0700	Nano Wallet Desktop Helper	GVA info: preferred scaler idx 0
error	15:54:39.881756 -0700	nano-wallet-desktop	nw_path_close_fd Failed to close guarded necp fd 32 [9: Bad file descriptor]
default	15:54:49.076333 -0700	nano-wallet-desktop	LSExceptions shared instance invalidated for timeout.
```

I guess I'll try building from source now.

**Comment by canted** [comment] 2018-07-17 17:49
I updated to 1.0.0 and the issue is gone 🙆‍♂️

**Comment by devinus** [comment] 2018-07-23 02:48
@GeniusUnleashed Can you confirm if this is still a problem for you with 1.0.1?

**Comment by GeniusUnleashed** [comment] 2018-07-23 23:16
@devinus Latest update is working now.

**Comment by zhyatt** [comment] 2020-10-12 15:38
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.

**Closed by zhyatt** 2020-10-12 15:38 UTC
